"""
pyduck-janitor: DuckDB-backed pyjanitor for high-performance data cleaning

This package combines the clean API of pyjanitor with the speed and
scalability of DuckDB for processing large datasets.
"""

from .duck_janitor import DuckJanitor
from .cleaning_ops import (
    clean_names,
    remove_columns,
    add_column,
    rename_column,
    dropna,
    remove_empty,
    filter_column,
    filter_on,
    filter_string,
    coalesce,
    encode_categorical,
    get_dummies,
    select_columns,
    select_rows,
    transform_column,
    transform_columns,
)
from .cleaning_ops_extended import (
    bin_numeric,
    change_type,
    concatenate_columns,
    deconcatenate_column,
    drop_constant_columns,
    fill,
    fill_empty,
    flag_nulls,
    limit_column_characters,
    min_max_scale,
    groupby_agg,
    groupby_topk,
    case_when,
    currency_column_to_numeric,
    convert_date,
    truncate_datetime,
    truncate_datetime,
    pivot_wider,
    pivot_longer,
)
from .cleaning_ops_final import (
    conditional_join,
    get_dupes,
    dropnotnull,
    expand_column,
    impute,
    jitter,
    label_encode,
    find_replace,
    count_cumulative_unique,
    complete,
    also,
    alias,
    mutate,
)

__version__ = "0.1.0"
__author__ = "Your Name"
__all__ = [
    "DuckJanitor",
    "clean_names",
    "remove_columns",
    "add_column",
    "rename_column",
    "dropna",
    "remove_empty",
    "filter_on",
    "filter_string",
    "filter_column",
    "coalesce",
    "encode_categorical",
    "get_dummies",
    "select_columns",
    "select_rows",
    "transform_column",
    "transform_columns",
    "bin_numeric",
    "change_type",
    "concatenate_columns",
    "deconcatenate_column",
    "drop_constant_columns",
    "fill",
    "fill_empty",
    "flag_nulls",
    "limit_column_characters",
    "min_max_scale",
    "groupby_agg",
    "groupby_topk",
    "case_when",
    "currency_column_to_numeric",
    "convert_date",
    "truncate_datetime",
    "pivot_wider",
    "pivot_longer",
    "conditional_join",
    "get_dupes",
    "dropnotnull",
    "expand_column",
    "impute",
    "jitter",
    "label_encode",
    "find_replace",
    "count_cumulative_unique",
    "complete",
    "also",
    "alias",
    "mutate",
]
