"""
pyduck-janitor: DuckDB-backed pyjanitor for high-performance data cleaning

This package combines the clean API of pyjanitor with the speed and
scalability of DuckDB for processing large datasets.
"""

from .cleaning_ops import (
    add_column,
    clean_names,
    coalesce,
    dropna,
    encode_categorical,
    filter_column,
    filter_on,
    filter_string,
    get_dummies,
    remove_columns,
    remove_empty,
    rename_column,
    select_columns,
    select_rows,
    transform_column,
    transform_columns,
)
from .cleaning_ops_extended import (
    bin_numeric,
    case_when,
    change_type,
    concatenate_columns,
    convert_date,
    currency_column_to_numeric,
    deconcatenate_column,
    drop_constant_columns,
    fill,
    fill_empty,
    flag_nulls,
    groupby_agg,
    groupby_topk,
    limit_column_characters,
    min_max_scale,
    pivot_longer,
    pivot_wider,
    truncate_datetime,
)
from .cleaning_ops_final import (
    alias,
    also,
    compare_df_cols,
    complete,
    conditional_join,
    count_cumulative_unique,
    drop_duplicate_columns,
    dropnotnull,
    expand_column,
    find_replace,
    get_dupes,
    impute,
    jitter,
    join_apply,
    label_encode,
    mutate,
    process_text,
)
from .duck_janitor import DropLabel, DuckJanitor, patterns
from .extensions import ExtensionNotAvailable
from .text_ops import (
    build_fts_index,
    drop_fts_index,
    keyword_filter,
    search_text,
    text_normalize,
)
from .embeddings import (
    DEFAULT_EMBED_MODEL,
    EmbeddingsNotAvailable,
    build_vector_index,
    cache_dir,
    embed_column,
    embed_install,
    embed_list_installed,
    embed_remove,
    fuzzy_dedupe,
    vector_search,
)

__version__ = "0.2.0"
__author__ = "EzraAir555"
__all__ = [
    "DuckJanitor",
    "clean_names",
    "remove_columns",
    "add_column",
    "rename_column",
    "dropna",
    "remove_empty",
    "filter_on",
    "filter_string",
    "filter_column",
    "coalesce",
    "encode_categorical",
    "get_dummies",
    "select_columns",
    "select_rows",
    "transform_column",
    "transform_columns",
    "bin_numeric",
    "change_type",
    "concatenate_columns",
    "deconcatenate_column",
    "drop_constant_columns",
    "fill",
    "fill_empty",
    "flag_nulls",
    "limit_column_characters",
    "min_max_scale",
    "groupby_agg",
    "groupby_topk",
    "case_when",
    "currency_column_to_numeric",
    "convert_date",
    "truncate_datetime",
    "pivot_wider",
    "pivot_longer",
    "conditional_join",
    "get_dupes",
    "dropnotnull",
    "expand_column",
    "impute",
    "jitter",
    "label_encode",
    "find_replace",
    "count_cumulative_unique",
    "complete",
    "also",
    "alias",
    "mutate",
    "drop_duplicate_columns",
    "compare_df_cols",
    "join_apply",
    "process_text",
    # pyjanitor helper surface (non-chained-verb)
    "DropLabel",
    "patterns",
]


# Append new exports to __all__
__all__ = __all__ + [
    # Text + similarity extensions (icu / fts / vss)
    "ExtensionNotAvailable",
    "EmbeddingsNotAvailable",
    "DEFAULT_EMBED_MODEL",
    "text_normalize",
    "build_fts_index",
    "drop_fts_index",
    "search_text",
    "keyword_filter",
    "embed_install",
    "embed_list_installed",
    "embed_remove",
    "cache_dir",
    "embed_column",
    "build_vector_index",
    "vector_search",
    "fuzzy_dedupe",
]
